
server:
  port: 9095

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/aluno
        password: '12345'
        username: root
    jpa:
        database-platform: org.hibernate.dialect.postgresqldialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
