
server:
  port: 9094
  
spring:
    datasource:
        data: classpath:/sql/data.sql
        driver-class-name: com.mysql.jdbc.Driver
        password: '1234'
        platform: mysql
        schema: classpath:/sql/schema.sql
        url: jdbc:mysql://localhost/oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
  authserver:
  hostname: http://localhost:9092
  security:
    oauth2:
      resource:
        accessTokenUri: http://api/uaa-service/uaa/oauth/token
        userAuthorizationUri: /uaa/oauth/token
  
  zuul:
    prefix: /api
    ignoredServices: '*'
    routes:
      uaa:
        path: /uaa/**
        sensitiveHeaders:
        serviceId: SEMPREUFG-AUTH-SERVER
      eventos:
        path: /evento/**
        sensitiveHeaders:
        serviceId: sempreufg-evento-service
